version: '2.3'
services:
  db:
    image: mysql:5.7
    ports:
      - '3360:3306'
    # volumes:
    #   - datastore
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: database
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
    tty: true